### ISSUE TITLE
Not working on 1.6.2 version

### ISSUE THREAD

**Issue by Tmos123** [Razer2015/NordeaRootBypasser#8]
Nordea Code app stopped working on the 22.1.2019 update. Version 1.6.2.

**Comment by Razer2015** [comment]
@derkommutator @Tmos123 @AnIK2k17 @Zerrika @DefiantCatgirl @pati610 

If any of you could test and report back if this works or not, I would appreciate it. I've only been able to test on my old S2 and it doesn't have xposed.
https://github.com/Razer2015/NordeaRootBypasser/releases/tag/v1.4

**Comment by Tmos123** [comment]
Not working. The codes app crashes in the activation phase after installing.

**Comment by DefiantCatgirl** [comment]
No idea how helpful this will be, considering all the obfuscation, but this is the crash when using the 1.4 release. Happens either on app startup if already registered, or right after entering the 10-digit code if it's a fresh install. OnePlus One, COS 13 (Android 6.0.1), Xposed 88.

```
03-04 17:54:56.527 14963-14963/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
03-04 17:54:56.527 14963-14963/? W/System.err:     at o.ɨ.ˋ(:172)
03-04 17:54:56.527 14963-14963/? W/System.err:     at o.ɨ.ˋ(:111)
03-04 17:54:56.527 14963-14963/? W/System.err:     at o.ﺩ.ˏ(Unknown Source)
03-04 17:54:56.527 14963-14963/? W/System.err:     at o.cg.ˎ(:65)
03-04 17:54:56.527 14963-14963/? W/System.err:     at o.co$if.ˎ(:95)
03-04 17:54:56.527 14963-14963/? W/System.err:     at o.co$if.ˎ(:95)
03-04 17:54:56.527 14963-14963/? W/System.err:     at o.cr$ˊ.run(:88)
03-04 17:54:56.527 14963-14963/? W/System.err:     at o.bb$ˋ.run(:119)
03-04 17:54:56.527 14963-14963/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
03-04 17:54:56.527 14963-14963/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-04 17:54:56.527 14963-14963/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
03-04 17:54:56.527 14963-14963/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5461)
03-04 17:54:56.527 14963-14963/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-04 17:54:56.527 14963-14963/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-04 17:54:56.527 14963-14963/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-04 17:54:56.528 14963-14963/? W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
03-04 17:54:56.587 1653-6235/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=484106, fe80::a0c9:a0ff:fef8:a0d7, [A2C9A0F8A0D7], RTM_NEWNEIGH, NUD_STALE}
                                                        
                                                        --------- beginning of crash
03-04 17:54:56.596 14963-14963/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.nordea.mobiletoken, PID: 14963
                                                   Theme: themes:{default=overlay:com.cyngn.hexo, iconPack:system, fontPkg:com.cyngn.hexo, com.android.systemui=overlay:com.cyngn.hexo, com.android.systemui.navbar=overlay:com.cyngn.hexo}
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                       at o.ɨ.ˋ(:172)
                                                       at o.ɨ.ˋ(:111)
                                                       at o.ﺩ.ˏ(Unknown Source)
                                                       at o.cg.ˎ(:65)
                                                       at o.co$if.ˎ(:95)
                                                       at o.co$if.ˎ(:95)
                                                       at o.cr$ˊ.run(:88)
                                                       at o.bb$ˋ.run(:119)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
03-04 17:54:56.600 1653-3846/? W/ActivityManager:   Force finishing activity com.nordea.mobiletoken/.enroll.EnrolmentActivity
```
